services:
  app:
    image: bellsoft/liberica-openjdk-alpine:11.0.16.1-1
    command: java -classpath /app/out ru.gb.jcore.sample.Main
      javadoc -d docs -sourcepath ./src -cp ./out -subpackages ru
    volumes:
      - ./bin:/app/out